services:
  web:
    ports:
      - "8080:80"
    build:
      context: .
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  php_myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
