name: CI

on:
    push:
        branches: [develop]
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.5"
                  extensions: pdo, pdo_mysql

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist

            - name: Run PHP Stan
              run: vendor/bin/phpstan analyse src
